# Generated by Django 4.2.11 on 2025-10-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=128)),
                ("order", models.PositiveIntegerField()),
                ("summary", models.TextField()),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("sheet", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "auto_approval_threshold",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("dependent_sheets", models.JSONField(blank=True, default=list)),
                (
                    "approval_roles",
                    models.ManyToManyField(
                        blank=True, related_name="finance_workflows", to="identity.role"
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="finance.phase",
                    ),
                ),
            ],
            options={
                "ordering": ("phase__order", "name"),
            },
        ),
        migrations.CreateModel(
            name="PhaseOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("sheet", models.CharField(max_length=128)),
                (
                    "audience",
                    models.ManyToManyField(
                        blank=True, related_name="finance_outputs", to="identity.role"
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="finance.phase",
                    ),
                ),
            ],
            options={
                "ordering": ("phase__order", "label"),
            },
        ),
    ]
