# Generated by Django 4.2.11 on 2025-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "hierarchy_level",
                    models.PositiveSmallIntegerField(
                        help_text="Lower numbers indicate higher privileges."
                    ),
                ),
            ],
            options={
                "ordering": ("hierarchy_level", "slug"),
            },
        ),
        migrations.CreateModel(
            name="RoleBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "roles",
                    models.ManyToManyField(related_name="bundles", to="identity.role"),
                ),
            ],
            options={
                "ordering": ("key",),
            },
        ),
    ]
