# Generated by Django 4.2.11 on 2025-10-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "audience",
                    models.ManyToManyField(
                        related_name="dashboards", to="identity.role"
                    ),
                ),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="DashboardKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("target_value", models.CharField(max_length=64)),
                ("status_description", models.CharField(max_length=128)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ("dashboard__slug", "label"),
            },
        ),
        migrations.CreateModel(
            name="DashboardAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("target_url", models.CharField(max_length=256)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ("dashboard__slug", "label"),
            },
        ),
    ]
