# Generated by Django 4.2.11 on 2025-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("trigger_condition", models.CharField(max_length=256)),
                ("sheet", models.CharField(blank=True, max_length=128)),
                (
                    "audience",
                    models.ManyToManyField(
                        related_name="alert_rules", to="identity.role"
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="AlertChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=16,
                    ),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="channels",
                        to="notifications.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
