name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  ci:
    name: Lint, test and package
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest ruff

      - name: Run CI script
        env:
          CI_SKIP_BYTECODE: "1"
        run: ./scripts/run_ci.sh

      - name: Upload compiled artifacts
        if: success() && hashFiles('build-artifacts/bytecode.tar.gz') != ''
        uses: actions/upload-artifact@v4
        with:
          name: compiled-bytecode
          path: build-artifacts/bytecode.tar.gz
