name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check .

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run pytest
        run: pytest

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare artifact directory
        run: mkdir -p build-artifacts

      - name: Compile sources
        run: |
          python -m compileall .
          find . -name '__pycache__' -type d -print > cache-dirs.txt
          tar -czf build-artifacts/bytecode.tar.gz -T cache-dirs.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-bytecode
          path: build-artifacts/bytecode.tar.gz
