name: CI

on:
  push:
    branches: ["main", "master", "develop", "ci-test", "*/*"]
  pull_request:
  workflow_dispatch:

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install quality dependencies
        if: hashFiles('requirements-dev.txt') != ''
        run: pip install -r requirements-dev.txt

      - name: Install Ruff linter
        run: pip install --upgrade pip ruff

      - name: Run Ruff linting
        run: ruff check .

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover

  build-modelo:
    name: Build Modelo
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build artifacts
        run: |
          mkdir -p build
          python -m compileall .
          echo "Build completado" > build/resumen.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modelo-build
          path: build/
