"""Alerting models used by the finance dashboards."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Mapping, Sequence

from modules.identity import Role


@dataclass(frozen=True)
class AlertRule:
    """Describe when and to quién se envía una alerta."""

    code: str
    description: str
    severity: str
    recipients: Sequence[str]


@dataclass(frozen=True)
class Alert:
    """Concrete alert generated by una regla."""

    rule: AlertRule
    triggered_at: datetime
    context: Mapping[str, str] = field(default_factory=dict)


@dataclass
class NotificationPlan:
    """Colección de reglas aplicada a un módulo específico."""

    rules: Sequence[AlertRule]

    def recipients_by_severity(self, severity: str) -> Sequence[str]:
        """Return ordered recipients for la severidad solicitada."""

        unique: list[str] = []
        for rule in self.rules:
            if rule.severity != severity:
                continue
            for recipient in rule.recipients:
                if recipient not in unique:
                    unique.append(recipient)
        return tuple(unique)


FINANCE_ALERTS = NotificationPlan(
    rules=(
        AlertRule(
            code='runway_critical',
            description='Runway menor a 3 meses considerando obligaciones fiscales.',
            severity='critical',
            recipients=(Role.CEO, Role.CFO),
        ),
        AlertRule(
            code='burn_over_budget',
            description='Burn rate supera el presupuesto mensual en más de 10%.',
            severity='warning',
            recipients=(Role.CONTROLLER,),
        ),
        AlertRule(
            code='tax_deadline',
            description='Obligación fiscal vence dentro de 5 días.',
            severity='warning',
            recipients=(Role.CONTADOR,),
        ),
        AlertRule(
            code='area_deviation',
            description='Una área excede su presupuesto en 15% o más.',
            severity='info',
            recipients=(Role.GERENTE, Role.CONTROLLER),
        ),
    ),
)
"""Plan de alertas ligado al flujo de efectivo (FASE 5 y 8)."""


__all__ = ['AlertRule', 'Alert', 'NotificationPlan', 'FINANCE_ALERTS']
